Algoritmo "Área do Circulo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/07/2023
Var
// Seção de Declarações das variáveis 
area, raio: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Digite o raio do círculo:")
leia(raio)

area <- 3.14 * raio * raio

escreval("    ")
escreval("A área do círculo é:" , area)


Fimalgoritmo